### ISSUE TITLE
Skip Links

### ISSUE THREAD

**Issue by anormand** [unimelb/The-University-of-Melbourne-Web-Templates#10]
### Problem:

The ‘Skip to ‘Navigation’ and ‘Skip to Content’ links have been disabled. 66% of screen reader users use skip links sometimes or often. The University of Melbourne web site uses skip links reasonably consistently across the site. Removing them on the Library site is likely to make things more difficult for users.
### WCAG Guideline

Success Criteria 3.2.3 – Consistent Navigation

Navigational mechanisms that are repeated on multiple pages within a set of Web pages occur in the same relative order each time they are repeated, unless a change is initiated by the user.
### Remedy:

Edit line 38 of styles.css.
### Example

Change
`.skiplinks   { display: none;}`

to
`.skiplinks {
    position: absolute;
    left: -900em;
    width: 100em;
    overflow: hidden;
}`

**Comment by kolber** [comment]
Thanks Andrew. We have just pushed out the updated header & footer code which addresses the usability issues highlighted in your last round of testing. This issue has been addressed within that.

**Comment by ptagell** [comment]
Have just looked at the most recent deploy 094 - and can confirm that there is no skip links. AK, can you look into it? Could be a merge thing

## 

Paul Tagell
Sent with Sparrow (http://www.sparrowmailapp.com)

**Comment by kolber** [comment]
These are injected with the header, so don't come with the standard template download. As far as I can see these are currently injected as expected.

**Comment by anormand** [comment]
Yes, I think this is fixed.
