### ISSUE TITLE
Image alt text

### ISSUE THREAD

**Issue by anormand** [unimelb/The-University-of-Melbourne-Web-Templates#3]
### Expert reviewer's comment:

> The alt attributes on this page contain the word "image", which is redundant, 
> as the user's assistive technology will typically identify the objects as images; 
> I would remove it.
### Remedy:

In index.html change:
`<img src="images/page-preview.png" height="100%" width="100%" alt="newsbanner feature image"></a>`

to
`<img src="images/page-preview.png" height="100%" width="100%" alt="newsbanner feature"></a>`

**Comment by ptagell** [comment]
Good point. Will add to 0-9-4
