### ISSUE TITLE
First links on page dont work at all.

### ISSUE THREAD

**Issue by ghost** [unimelb/The-University-of-Melbourne-Web-Templates#31]
I tried dropping the html from documentation on how to use best:

```
http://brand.unimelb.edu.au/web/docs/docs/docs/
```

Into a test app:

```
http://vote-uat.unimelb.edu.au/
```

And my first problem is that the links across the top of the page dont work. What is the proposed way to work around this?

**Comment by ptagell** [comment]
Hi there,

Are you talking about the Study et al links?

The links should work, but may not work locally. On your test site Study et
al all work for me.

Regards,
Paul

**Comment by ghost** [comment]
Aaah, that explains it. Odd that it would only work on a real site (: Didn't expect that.
