### ISSUE TITLE
Heading tags

### ISSUE THREAD

**Issue by anormand** [unimelb/The-University-of-Melbourne-Web-Templates#4]
### Expert reviewer's comment:

> The use of headings would be clearer if content were added, I think. 
> As it stands, the headings are a helpful navigational aid, 
> but their contents aren't always heading-like, which could be confusing.
### Remedy:

Some of the headings in index.html are really content. For example, the text 'From February 22-25 Get Involved, get connected' is presented as a heading, when really it is content.
### Example:

Change
`<div class="banner-text">
    <h2><a href="http://newsroom.melbourne.edu/studio/ep-92">Graduate Access Melbourne</a></h2>
    <h3><a href="http://newsroom.melbourne.edu/studio/ep-92">From February 22&ndash;25<br>
    Get involved, get connected</a></h3>
</div>`

to
`<div class="banner-text">
              <h2><a href="http://newsroom.melbourne.edu/studio/ep-92">Graduate Access Melbourne</a></h2>
              <p><a href="http://newsroom.melbourne.edu/studio/ep-92">From February 22&ndash;25<br>
                Get involved, get connected</a></p>
</div>`

**Comment by ptagell** [comment]
Easy fix. Will add to 0-9-4
