### ISSUE TITLE
Change <label> styles

### ISSUE THREAD

**Issue by rothenburycam** [unimelb/The-University-of-Melbourne-Web-Templates#47]
Could the <label> styles please be changed from display:inline-block to display:block? It makes elements below (particularly notes created by the CMS form builder) float up against it in desktop and mobile view. Screenshots attached.

`@media screen and (min-width: 769px)`
`.uomcontent fieldset label {`
`width: 412px;`
`width: 25.75rem;`
`display: inline-block;`
`}`

Screenshots below: 

<img width="369" alt="screen shot 2016-03-08 at 9 40 04 am" src="https://cloud.githubusercontent.com/assets/11714609/13585787/ee6904c0-e511-11e5-8ff6-a3e60ff24122.png">
<img width="368" alt="screen shot 2016-03-08 at 9 39 56 am" src="https://cloud.githubusercontent.com/assets/11714609/13585789/ee6cf260-e511-11e5-948e-574167fd8c91.png">
<img width="677" alt="screen shot 2016-03-08 at 9 39 01 am" src="https://cloud.githubusercontent.com/assets/11714609/13585788/ee69dcb0-e511-11e5-8697-6a126a90806b.png">
<img width="670" alt="screen shot 2016-03-08 at 9 38 12 am" src="https://cloud.githubusercontent.com/assets/11714609/13585790/ee6d5b88-e511-11e5-8ba3-228f9c5e0bd2.png">

**Comment by waitingallday** [comment]
Wow how did you even find this repo! :smile: I think you mean https://github.com/marcom-unimelb/unimelb-design-system

**Comment by rothenburycam** [comment]
Whoop! Thanks Jason haha.
