### ISSUE TITLE
First paragraph

### ISSUE THREAD

**Issue by anormand** [unimelb/The-University-of-Melbourne-Web-Templates#5]
### Expert reviewer's comment:

> The other notable oddity, which isn't really a major accessibility issue, 
> is that in your templates, there is a paragraph preceding the first heading.
> Anyone who is navigating back and forth by headings will miss it, obviously,
> but the paragraph will be presented immediately after the page is loaded, as
> the focus is at the start of the document.
### Discussion:

Interesting observation. I will look into this further.

**Comment by ptagell** [comment]
Yeah it's interesting. When you think about it, that may actually a redundancy brought over from the earlier templates. There may be no need for it. For example, if you're on the GSBE website, do you reallly need to know that this is part of the Faculty of Business and Economics? Not really....

I've started scrapping it from any central sites - it just meant that The University of Melbourne was next to a logo that also said "The University of Melbourne" 

Thoughts?
