### ISSUE TITLE
Radio button labels

### ISSUE THREAD

**Issue by anormand** [unimelb/The-University-of-Melbourne-Web-Templates#6]
### Expert reviewer's comment

> The forms were also accessible, except that I couldn't select the first option
> of the "gender" form - it appears to be a straightforward HTML form, so it's
> probably another Mozilla bug that you won't have to consider as it will almost
> certainly go away soon. If any Javascript touches it, though, then that's a
> different story.
### Problem

This appears to be caused by a known issue as described in [WCAG Technique H44](http://www.w3.org/TR/WCAG-TECHS/H44.html): 
The HTML and XHTML specifications allow both implicit and explicit labels. However, some assistive technologies do not correctly handle implicit labels (for example, `<label>First name <input type="text" name="firstname"></label>`).
### Remedy

Use legends to identify groups of form controls. See  [WCAG Technique H71](http://www.w3.org/TR/WCAG-TECHS/H71.html).
Explicitly associate labels with input fields using 'for' and 'id' attributes.
CSS will need to be adjusted.
### Radio Button Example

Change
`<fieldset>
          <h4>Gender</h4>
          <legend class="col-2">Gender</legend>
          <div class="follower col-3">
              <input type="radio" name="gender" value="male" id="male">
            <label for="male">Male</label>
              <input type="radio" id="female" value="female" name="gender">
            <label for="female">Female
            </label>
              <input type="radio" id="other" value="other" name="gender">
               <label for="other">Neither of these terms describe me
            </label>
          </div>
 </fieldset>`

to
`<fieldset>
          <h4>Gender</h4>
          <legend class="col-2">Gender</legend>
          <div class="follower col-3">
              <input type="radio" id="male" value="male" name="gender">
            <label for="male">Male</label>
              <input type="radio" name="gender" value="female" id="female">
            <label for="female">Female
            </label>
              <input type="radio" name="gender" value="other" id="other">
               <label for="other">Neither of these terms describe me
            </label>
          </div>
</fieldset>`
### Check Box Example

Change
`<fieldset>
          <h4>Dietary Requirements</h4>
          <label class="col-2" for="gluten">Requirements</label>
          <div class="follower col-3">
            <label>
              <input type="checkbox" id="gluten" value="gluten" name="dietary-requirements">
              Gluten allergies
            </label>
            <label>
              <input type="checkbox" id="lactose" value="lactose" name="dietary-requirements">
              Lactose intolerant
            </label>
            <label>
              <input type="checkbox" id="bananas" value="other" name="dietary-requirements">
              Don't like bananas
            </label>
          </div>
</fieldset>`

to
`<fieldset>
          <h4>Dietary Requirements</h4>
          <legend class="col-2">Requirements</legend>
          <div class="follower col-3">
              <input type="checkbox" id="gluten" value="gluten" name="dietary-requirements">
              <label for="gluten">Gluten allergies</label>
              <input type="checkbox" id="lactose" value="lactose" name="dietary-requirements">
              <label for="lactose">Lactose intolerant</label>
              <input type="checkbox" id="bananas" value="other" name="dietary-requirements">
              <label for="bananas">Don't like bananas</label>
          </div>
</fieldset>`

**Comment by ptagell** [comment]
Have changed "labels" to legends and adjusted CSS to suit.

**Comment by ptagell** [comment]
Added for attributes to the labels. This should make the explicit rather than implicit.

**Comment by anormand** [comment]
That's great, but legends aren't needed for the "What can we do for you?' and 'What size head do you have?' examples. They were fine as they were previously.

**Comment by ptagell** [comment]
Ok - have removed and send through a new package

**Comment by anormand** [comment]
Sorry, legends now missing for 'Basic Details' and 'Gender'.

**Comment by anormand** [comment]
### Expert reviewer's comment

> It's much improved now.
