### ISSUE TITLE
Mobile template ARIA landmarks

### ISSUE THREAD

**Issue by anormand** [unimelb/The-University-of-Melbourne-Web-Templates#8]
### Problem:

The drop down navigation menu doesn't have an ARIA role assigned to it.
### Remedy

Add an ARIA role to the navigation. 
### Example

Change
`<div class="mobile-nav">`

to
`<div class="mobile-nav" role=”navigation”>`
### Notes

This is another outstanding issue from the 0.9.2 report

**Comment by ptagell** [comment]
Hmmm...I'm sure we made those changes. Something must've not deployed.

**Comment by anormand** [comment]
Paul,

Just letting you know that I am waiting on these changes to be redeployed
before I can get the expert reviewer to do the final testing.

Cheers

Andy

On 16/06/11 3:14 PM, "ptagell"
reply@reply.github.com
wrote:

**Comment by kolber** [comment]
These issues were lost somewhere in our commit history. They have been restored and will be released this afternoon.
